In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
df.shape

(150, 5)

In [11]:
X = df.drop('species',axis=1)
y = df['species']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=3)
model_knn.fit(X_train, y_train)
model_knn.score(X_test,y_test)

1.0

In [19]:
from sklearn.svm import SVC
model_svc = SVC(gamma='auto', C=10)
model_svc.fit(X_train, y_train)
model_svc.score(X_test,y_test)

1.0

In [23]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C' : [0.1,1,10,20],
              'gamma' : ['auto', 'scale'],
              'kernel' : ['rbf', 'linear']
             }
model_grid_search = GridSearchCV(model_svc, param_grid, cv =5)
model_grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(C=10, gamma='auto'),
             param_grid={'C': [0.1, 1, 10, 20], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [25]:
model_grid_search.cv_results_

{'mean_fit_time': array([0.00223956, 0.00053387, 0.0005856 , 0.00049076, 0.00049   ,
        0.00044107, 0.00070486, 0.00051212, 0.00052962, 0.00061603,
        0.00057349, 0.00059323, 0.00048823, 0.00045438, 0.00046959,
        0.000453  ]),
 'std_fit_time': array([9.00742017e-04, 6.91943788e-05, 1.07889610e-05, 3.12030082e-05,
        3.09380238e-05, 6.99505647e-06, 1.14130015e-04, 7.31844849e-05,
        8.41125880e-05, 1.14195023e-04, 2.16924748e-05, 8.51064699e-05,
        2.83561391e-05, 1.41560416e-05, 2.12396566e-05, 2.55519766e-05]),
 'mean_score_time': array([0.00145354, 0.00035806, 0.00039454, 0.00033507, 0.00034695,
        0.0003139 , 0.00050044, 0.00037203, 0.00036926, 0.0004303 ,
        0.00038877, 0.00040221, 0.00033298, 0.00031357, 0.0003408 ,
        0.00031104]),
 'std_score_time': array([6.44876195e-04, 2.28525918e-05, 1.56220761e-05, 8.51471492e-06,
        2.37900170e-05, 3.39057709e-06, 1.38041598e-04, 6.06162252e-05,
        7.99726285e-05, 3.89025485e-05, 3.72716494e-05, 9.53674316e-06,
        4.74590732e-06, 5.00883333e-06, 2.29826606e-05, 1.01450958e-05]),
 'param_C': masked_array(data=[0.1, 0.1, 0.1, 0.1, 1, 1, 1, 1, 10, 10, 10, 10, 20, 20,
                    20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_gamma': masked_array(data=['auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'}],
 'split0_test_score': array([1.        , 1.        , 0.95833333, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.95833333, 0.95833333, 1.        ,
        0.95833333]),
 'split1_test_score': array([0.875     , 0.91666667, 0.75      , 0.91666667, 0.95833333,
        0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333,
        0.95833333, 0.95833333, 0.95833333, 0.95833333, 0.95833333,
        0.95833333]),
 'split2_test_score': array([0.875     , 0.83333333, 0.91666667, 0.83333333, 0.83333333,
        0.875     , 0.83333333, 0.875     , 0.83333333, 0.83333333,
        0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
        0.83333333]),
 'split3_test_score': array([0.95833333, 1.        , 0.95833333, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.95833333,
        1.        , 0.95833333, 1.        , 1.        , 1.        ,
        1.        ]),
 'split4_test_score': array([0.875     , 0.95833333, 0.875     , 0.95833333, 0.95833333,
        0.95833333, 0.95833333, 0.95833333, 1.        , 1.        ,
        0.95833333, 1.        , 1.        , 1.        , 1.        ,
        1.        ]),
 'mean_test_score': array([0.91666667, 0.94166667, 0.89166667, 0.94166667, 0.95      ,
        0.95833333, 0.95      , 0.95833333, 0.95833333, 0.95      ,
        0.95      , 0.95      , 0.95      , 0.95      , 0.95833333,
        0.95      ]),
 'std_test_score': array([0.05270463, 0.06236096, 0.07728015, 0.06236096, 0.06123724,
        0.04564355, 0.06123724, 0.04564355, 0.06454972, 0.06123724,
        0.06123724, 0.06123724, 0.06123724, 0.06123724, 0.06454972,
        0.06123724]),
 'rank_test_score': array([15, 13, 16, 13,  5,  1,  5,  1,  1,  5,  5,  5,  5,  5,  1,  5],
       dtype=int32)}

In [29]:
results = pd.DataFrame(model_grid_search.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002240,0.000901,0.001454,0.000645,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",1.000000,0.875000,0.875000,0.958333,0.875000,0.916667,0.052705,15
1,0.000534,0.000069,0.000358,0.000023,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,0.916667,0.833333,1.000000,0.958333,0.941667,0.062361,13
2,0.000586,0.000011,0.000395,0.000016,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.958333,0.750000,0.916667,0.958333,0.875000,0.891667,0.077280,16
3,0.000491,0.000031,0.000335,0.000009,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,0.916667,0.833333,1.000000,0.958333,0.941667,0.062361,13
4,0.000490,0.000031,0.000347,0.000024,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,5
5,0.000441,0.000007,0.000314,0.000003,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
6,0.000705,0.000114,0.000500,0.000138,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,5
7,0.000512,0.000073,0.000372,0.000061,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
8,0.000530,0.000084,0.000369,0.000080,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
9,0.000616,0.000114,0.000430,0.000039,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,5
10,0.000573,0.000022,0.000389,0.000037,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,5
11,0.000593,0.000085,0.000402,0.000010,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,5
12,0.000488,0.000028,0.000333,0.000005,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,5
13,0.000454,0.000014,0.000314,0.000005,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,5
14,0.000470,0.000021,0.000341,0.000023,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1
15,0.000453,0.000026,0.000311,0.000010,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,5

In [31]:
results[['params', 'mean_test_score']]

                                              params  mean_test_score
0       {'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}         0.916667
1    {'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}         0.941667
2      {'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}         0.891667
3   {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}         0.941667
4         {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}         0.950000
5      {'C': 1, 'gamma': 'auto', 'kernel': 'linear'}         0.958333
6        {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}         0.950000
7     {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}         0.958333
8        {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}         0.958333
9     {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}         0.950000
10      {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}         0.950000
11   {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}         0.950000
12       {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}         0.950000
13    {'C': 20, 'gamma': 'auto', 'kernel': 'linear'}         0.950000
14      {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}         0.958333
15   {'C': 20, 'gamma': 'scale', 'kernel': 'linear'}         0.950000

In [33]:
param_grid = {'n_neighbors' : [3,5,7,9,11,13],
              'metric' : ['euclidean','manhattan']
             }
model_grid_search = GridSearchCV(model_knn, param_grid, cv =5)
model_grid_search.fit(X_train, y_train)
results = pd.DataFrame(model_grid_search.cv_results_)
results[['params', 'mean_test_score']]

                                        params  mean_test_score
0    {'metric': 'euclidean', 'n_neighbors': 3}         0.958333
1    {'metric': 'euclidean', 'n_neighbors': 5}         0.941667
2    {'metric': 'euclidean', 'n_neighbors': 7}         0.941667
3    {'metric': 'euclidean', 'n_neighbors': 9}         0.933333
4   {'metric': 'euclidean', 'n_neighbors': 11}         0.950000
5   {'metric': 'euclidean', 'n_neighbors': 13}         0.941667
6    {'metric': 'manhattan', 'n_neighbors': 3}         0.958333
7    {'metric': 'manhattan', 'n_neighbors': 5}         0.941667
8    {'metric': 'manhattan', 'n_neighbors': 7}         0.941667
9    {'metric': 'manhattan', 'n_neighbors': 9}         0.950000
10  {'metric': 'manhattan', 'n_neighbors': 11}         0.950000
11  {'metric': 'manhattan', 'n_neighbors': 13}         0.950000

In [35]:
from sklearn.model_selection import RandomizedSearchCV
param_grid = {'C' : [0.1,1,10,20],
              'gamma' : ['auto', 'scale'],
              'kernel' : ['rbf', 'linear']
             }
model_random_search = RandomizedSearchCV(model_svc, param_grid, cv =5, n_iter = 4)
model_random_search.fit(X_train, y_train)
results = pd.DataFrame(model_random_search.cv_results_)
results[['params', 'mean_test_score']]

                                            params  mean_test_score
0      {'kernel': 'rbf', 'gamma': 'scale', 'C': 1}         0.950000
1      {'kernel': 'rbf', 'gamma': 'auto', 'C': 10}         0.958333
2  {'kernel': 'linear', 'gamma': 'auto', 'C': 0.1}         0.941667
3  {'kernel': 'linear', 'gamma': 'scale', 'C': 10}         0.950000

In [37]:
param_grid = {'n_neighbors' : [3,5,7,9,11,13],
              'metric' : ['euclidean','manhattan']
             }
model_random_search = RandomizedSearchCV(model_knn, param_grid, cv =5, n_iter = 4)
model_random_search.fit(X_train, y_train)
results = pd.DataFrame(model_random_search.cv_results_)
results[['params', 'mean_test_score']]

                                       params  mean_test_score
0   {'n_neighbors': 5, 'metric': 'manhattan'}         0.941667
1   {'n_neighbors': 9, 'metric': 'manhattan'}         0.950000
2  {'n_neighbors': 11, 'metric': 'euclidean'}         0.950000
3   {'n_neighbors': 7, 'metric': 'manhattan'}         0.941667